#!/usr/bin/env python

import os, shlex, signal
from glob import glob
from subprocess import Popen
from flask import Flask, request, abort, redirect, jsonify

app = Flask(__name__)
go_cmd = '/usr/bin/goaccess -a -g --real-time-html -p %s --port %d'
go_pid = {}  # dict of tuples { session: (pid,port) }

@app.route("/sites", methods=['GET'])
def sites():
    sites = {}
    paths = glob('/etc/gopanel/*.conf')
    for conf in paths:
        name,_ = os.path.splitext(os.path.basename(conf))
        title = get_conf_var(conf, 'html-report-title', name)
        sites[name] = title
    sess = request.args.get('session', None)
    if sess is None:
        return jsonify({'error':'no session'})
    if sess in go_pid:
        proc,port = go_pid[sess]
        proc.terminate()
        proc.wait()
        del go_pid[sess]
    return jsonify(sites)

@app.route("/run", methods=['GET'])
def run():
    conf = '/etc/gopanel/%s.conf' % request.args.get('site')
    paths = glob('/etc/gopanel/*.conf')
    if conf not in paths:
        return jsonify({'error':'invalid site'})
    sess = request.args.get('session', None)
    if sess is None:
        return jsonify({'error':'no session'})
    if sess in go_pid:
        proc,port = go_pid[sess]
        proc.terminate()
        proc.wait()
    else:
        port = get_conf_var(conf, 'port', 7890) #+ len(goPid)
    try:
        go_pid[sess] = Popen(shlex.split(go_cmd % (conf, int(port)))),port
    except Exception as e:
        return jsonify({'error':'goaccess'})
    return jsonify({'go':os.path.basename(get_conf_var(conf, 'output-format')),'sess':sess[:8],'pid':go_pid[sess][0].pid,'port':go_pid[sess][1]})

def get_conf_var(conf, key, default=None):
    with open(conf) as f:
        data = f.read().splitlines()
        for line in data:
            if len(line) > 0 and line[0] != '#':
                k,v = line.split(' ', 1)
                if k == key:
                    return v
    return default
 
if __name__ == "__main__":
    app.run(host='localhost', port=7880, debug=False)

